name: Build and Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --name="OGG-to-WAV" gui/app.py
      env:
        PYTHONIOENCODING: utf-8

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OGG-to-WAV
        path: dist/OGG-to-WAV.exe

    - name: VirusTotal GitHub Action
      uses: crazy-max/ghaction-virustotal@v4.0.0
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        files: dist/OGG-to-WAV.exe